import { op, jsonBody } from '../helpers.js';

export function preferencesPaths() {
  return {
    '/api/v1/preferences': {
      get: op({ summary: 'Get user preferences', tag: 'Preferences', description: 'Household preferences. Language fields: `language` (explicitly chosen data language, or `null` for automatic), plus two read-only values — `language_effective` (what actually applies: `language`, else the language part of `region`, else `en`) and `language_auto` (what automatic mode alone would yield, ignoring `language`). The data language decides in which language the server *stores* content it generates itself - birthday event titles, loan instalments, and the public/school holiday names pulled from OpenHolidays (#946) - so that the API, the ICS feed and calendar sync all agree. Changing it re-syncs the holiday cache on the next run, because that cache holds translated names rather than keys. Weather fields: `weather_provider` (`open-meteo` | `openweathermap` | `null` = auto-detect from env), `weather_lat`, `weather_lon`, `weather_city`, `weather_units` (`metric` | `imperial`). Holiday fields: `holiday_country` (ISO-3166 alpha-2 or `null`), `holiday_subdivision` (e.g. `DE-BY` or `null`), `holiday_group` (school-holiday group for multilingual cantons, e.g. `CH-BE-VS`, or `null`), `holiday_show_public`, `holiday_show_school` (booleans), `holiday_public_color`, `holiday_school_color` (hex), `holiday_last_sync`. Overview fields: `dashboard_widgets` (the tile arrangement that applies to the calling user) and `dashboard_today_glance` (header band on/off), plus `dashboard_widgets_default` / `dashboard_today_glance_default` (what the household published as its default, `dashboard_widgets_default` is `null` when nothing was published) and `dashboard_follows_default` (`true` when the caller has no arrangement of their own and therefore follows the household).' }),
      put: op({ summary: 'Update user preferences', tag: 'Preferences', description: '`language` is admin-only: an ISO-639-1 code with a locale file, or `null`/`""` to fall back to automatic derivation from `region`. Changing it (or `region`, or `date_format`) re-titles the stored birthday events so every channel stays consistent. `timezone` is admin-only too: an IANA zone (validated against ICU, so aliases like `Europe/Kiev` are accepted), or `null`/`""` to fall back to the `TZ` env var, then the host zone, then UTC. It is the household zone used wherever a time carries none of its own - the calendar day server-side jobs call "today", the zone of the exported ICS feed, and the clock time events arrive with in Google and Outlook. The GET response carries both views: `timezone` (what is chosen, `null` for automatic) and `timezone_effective` (what applies, never `null`). Weather fields (`weather_provider`, `weather_lat`, `weather_lon`, `weather_city`, `weather_units`) and holiday fields (`holiday_country`, `holiday_subdivision`, `holiday_group`, `holiday_show_public`, `holiday_show_school`, `holiday_public_color`, `holiday_school_color`) are admin-only. `weather_lat`/`weather_lon` are validated to ±90 / ±180; colors must be 6-digit hex. Module feature toggles `health_cycle_enabled` (show the health cycle tab household-wide) and `rewards_require_approval` (redemptions need admin approval) are admin-only booleans, both default `true`. `health_cycle_enabled_user` is the per-user opt-out for the same tab and is writable by anyone for themselves; it can only narrow the household setting, never widen it. The GET response exposes all three views: `health_cycle_enabled` (household), `health_cycle_enabled_user` (mine) and the read-only `health_cycle_effective` (both combined, which is what the UI renders). Overview fields: `dashboard_widgets` (array of `{id, visible, order, size, options?}`; `options` is stored but not interpreted - the server validates only its shape: a flat object, at most 8 keys, values boolean, finite number, short string or list of short strings) and `dashboard_today_glance` are personal and writable by anyone for themselves; sending `null` for either deletes the personal value, so the caller follows the household default again - including every later change to it. `dashboard_widgets_default` and `dashboard_today_glance_default` are the household default and admin-only; they never overwrite a member who has an arrangement of their own, and `null` removes the default.', stateChanging: true, requestBody: jsonBody(null) }),
    },
    '/api/v1/preferences/holidays/countries': { get: op({ summary: 'List countries supported for holidays', tag: 'Preferences', description: 'Proxies the OpenHolidays API (36 countries) and appends five further countries whose public holidays Yuvomi computes locally (US, CA, GB, AU, NZ - #965), when OpenHolidays does not already list them. Returns `{ data: [{ isoCode, name, schoolHolidays? }] }` for the country dropdown; `schoolHolidays: false` marks a locally computed country, none of which has school-holiday data available. When OpenHolidays is unreachable the response degrades to the locally computed countries instead of failing, so they stay selectable offline.' }) },
    '/api/v1/preferences/holidays/subdivisions/{countryCode}': { get: op({ summary: 'List subdivisions for a country', tag: 'Preferences', params: [{ name: 'countryCode', in: 'path', required: true, schema: { type: 'string', pattern: '^[A-Z]{2}$' } }], description: 'Proxies the OpenHolidays API, except for `GB` (not an OpenHolidays country - #965), which is answered locally with its three nations (`GB-ENG`, `GB-SCT`, `GB-NIR`), each with its own complete holiday list rather than a shared baseline. Returns `{ data: [{ isoCode, name }] }` for the state/region dropdown.' }) },
    '/api/v1/preferences/holidays/groups/{countryCode}/{subdivisionCode}': { get: op({ summary: 'List school-holiday groups for a subdivision', tag: 'Preferences', params: [{ name: 'countryCode', in: 'path', required: true, schema: { type: 'string', pattern: '^[A-Z]{2}$' } }, { name: 'subdivisionCode', in: 'path', required: true, schema: { type: 'string', pattern: '^[A-Z]{2}-[A-Z0-9-]{1,10}$' } }], description: 'Proxies the OpenHolidays API. Returns `{ data: [{ code, name }] }` of school-holiday groups (multilingual cantons such as `CH-BE` split into e.g. `CH-BE-VS` / `CH-BE-EO`). Empty when the subdivision has a single school-holiday regime. Used to disambiguate overlapping same-named holidays (#434).' }) },
    '/api/v1/preferences/holidays/sync': { post: op({ summary: 'Sync holidays for the configured country', tag: 'Preferences', admin: true, stateChanging: true, description: 'Fetches public/school holidays from OpenHolidays for the configured country/subdivision and caches them. Returns `{ data: { last_sync } }`.' }) },
  };
}
