import { op, jsonBody, idParam } from '../helpers.js';

export function rewardsPaths() {
  return {
    '/api/v1/rewards/overview': {
      get: op({ summary: 'Reward overview (balances, catalog, pending count)', tag: 'Rewards', description: '`pendingCount` counts the open REWARD requests, as it always has. Open pocket money requests (#1734) are counted separately in `moneyPendingCount`, and only those the caller may read: all for an administrator, the own for a member, none for a paired display.' }),
    },
    '/api/v1/rewards/participants': {
      get: op({ summary: 'List members with participation flag and balance', tag: 'Rewards', admin: true }),
    },
    '/api/v1/rewards/participants/{userId}': {
      put: op({ summary: 'Enable/disable a member in the reward system', tag: 'Rewards', admin: true, params: [idParam('userId', 'User ID')], stateChanging: true, requestBody: jsonBody(null) }),
    },
    '/api/v1/rewards/catalog': {
      get: op({ summary: 'List rewards (admin sees inactive with ?all=1)', tag: 'Rewards' }),
      post: op({ summary: 'Create reward', tag: 'Rewards', admin: true, stateChanging: true, requestBody: jsonBody(null), description: 'Body: { name, cost, icon?, description?, sort_order?, quantity? }. `quantity` is how many units the HOUSEHOLD has of this reward; omitted or `null` means unlimited, which is what every reward created before #1310 is. A listed reward also carries `remaining` - the units left, derived from the fulfilled redemptions, `null` when there is no limit.' }),
    },
    '/api/v1/rewards/catalog/{id}': {
      patch: op({ summary: 'Update / (de)activate reward', tag: 'Rewards', admin: true, params: [idParam()], stateChanging: true, requestBody: jsonBody(null), description: '`quantity` follows the same field vocabulary as `icon` and `description`: an absent field leaves it alone, `null` lifts the limit. Lowering it below what is already fulfilled is allowed - a household can lose an item - and `remaining` then reads 0.' }),
      delete: op({ summary: 'Delete reward', tag: 'Rewards', admin: true, params: [idParam()], stateChanging: true }),
    },
    '/api/v1/rewards/ledger': {
      get: op({ summary: 'Point transaction history (filter by user_id)', tag: 'Rewards', description: 'Every entry carries its person, points and type. `reason` and `task_id` of an entry that belongs to a task are `null` unless the entry is the caller\'s own or the caller can see that task (same rule as GET /tasks, no admin bypass); once the task is deleted they stay with the entry\'s owner. Bonus, adjustment and redemption entries keep their `reason` for everyone. Points only: pocket money entries live in the same ledger but never appear here (see GET /rewards/money/ledger).' }),
    },
    '/api/v1/rewards/redemptions': {
      get: op({ summary: 'List redemption requests (filter by status)', tag: 'Rewards', description: 'An administrator gets every request, everyone else only their own. Each row carries `user_balance`: the current point balance of the member the request is for, summed from the ledger at the time of the call (not the balance when the request was made). It is present for members who no longer take part in rewards as well, which `balances` in the overview is not, and it can be below zero. POCKET MONEY (#1734): without a `kind` query parameter the list is what it was before - reward requests only (`kind: "reward"`), so a client that sums `cost` as points keeps summing points. `?kind=money` answers the pocket money requests, `?kind=withdrawal` or `?kind=deposit` one sort, `?kind=all` both sorts together; any other value is 400. A money request carries the amount in minor units in `cost`, its `currency` and `minor_unit` (those of the account, not of today\'s household setting) and, while it is pending, the MONEY balance in `user_balance` (null once the request is decided: the account may since have been closed and reopened in another currency), and goes to the member it belongs to and to administrators only, never to a paired display.' }),
      post: op({ summary: 'Request a redemption (reserves points)', tag: 'Rewards', stateChanging: true, requestBody: jsonBody(null), description: 'Body: { catalog_id, user_id?, note? }. Points are reserved immediately; whether anyone has to approve stays with the household setting. `user_id` redeems on behalf of someone else and is otherwise ignored: an administrator may do it for any member, and a paired wall display must do it, naming the person chosen on the device (#1209). For a display the person is required rather than optional, because the display account takes no part in rewards itself, and it has to be a household member who may write this module. The request is booked as the display having asked and the person having received. A reward whose units are all fulfilled answers 409 with `reason: "out_of_stock"`; nothing is booked, so no points are taken. POCKET MONEY (#1734): with `kind: "withdrawal"` or `kind: "deposit"` the body is { kind, amount, note?, user_id? } and no catalogue entry is involved. `amount` is a decimal STRING in the currency of the ACCOUNT ("5.00"; whole units for a currency without decimals); an optional `currency` that is not the account\'s is 400 with `reason: "currency_mismatch"`; a number, an array or an object is 400, and so is a `note` that is not a string. Nothing is booked when the request is filed and it always waits for an administrator, whatever the approval setting says. The person needs a pocket money account (a plan or a money entry), otherwise 400 with `reason: "no_money_account"`. A withdrawal above the balance is 400 with `reason: "insufficient_funds"`. A paired display gets 403 with `reason: "money_not_on_display"`.' }),
    },
    '/api/v1/rewards/redemptions/{id}': {
      patch: op({ summary: 'Decide a redemption (fulfill/reject/cancel)', tag: 'Rewards', params: [idParam()], stateChanging: true, requestBody: jsonBody(null), description: 'Body: { action: "fulfill" | "reject" | "cancel" }. Fulfilling a request whose reward has no units left does not fail silently: the request is REJECTED with `decision_reason: "out_of_stock"`, the reserved points go back through the usual `reversal`, and the answer is 409 with `reason: "out_of_stock"` and the decided row in `data`. Rejecting and cancelling stay untouched - sold out means only that fulfilling finds no unit. POCKET MONEY (#1734): fulfilling a withdrawal books the amount off the money balance, fulfilling a deposit credits it; rejecting and cancelling book nothing, because nothing was reserved. The cover is checked again when a withdrawal is fulfilled: if the balance no longer covers it, the answer is 409 with `reason: "insufficient_funds"` and the request STAYS pending. When a member is deactivated, their open money requests are cancelled with `decision_reason: "account_deactivated"`; fulfilling one that is still open for a deactivated member cancels it and answers 409 with `reason: "account_deactivated"`. A money request the caller may not read (somebody else\'s, for a non-administrator) answers 404 for every action, exactly like an id that does not exist.' }),
    },
    '/api/v1/rewards/bonus': {
      post: op({ summary: 'Grant manual bonus / correction points', tag: 'Rewards', admin: true, stateChanging: true, requestBody: jsonBody(null) }),
    },
    '/api/v1/rewards/money': {
      get: op({ summary: 'Pocket money accounts the caller may see', tag: 'Rewards', description: 'Answers { currency, minor_unit, accounts, candidates }. An account is { id, display_name, balance_minor, currency, minor_unit, former, closable, plan } with `plan` either null or { amount_minor, currency, minor_unit, frequency, anchor_day, next_run_date, paused }. AN ACCOUNT IS A ROW OF ITS OWN AND HAS EXACTLY ONE CURRENCY: the household currency of the day it was opened. The code is also written on every money entry, every money request and the plan. A later change of the household currency leaves existing accounts as they are - read `currency` and `minor_unit` (decimals per ISO 4217) from the ACCOUNT, not from the top level, which names the household currency a NEW account would be opened in. `closable` is true for an account with no plan, balance zero and nothing pending; only such an account can be closed, and one opened again takes the household currency of then. `former: true` marks the account of a deactivated member that still holds a balance; only administrators get it, it can only be paid out, and it leaves the list at balance zero. WHO SEES WHAT: a member gets their own account or an empty list, an administrator gets every account, a paired display gets none. A scoped API token follows the same rule through its subject and role. Pocket money is separate from points: there is no conversion in either direction. `candidates` lists the members without an account and is filled for administrators only.' }),
    },
    '/api/v1/rewards/money/accounts': {
      post: op({ summary: 'Open a pocket money account for a member', tag: 'Rewards', admin: true, stateChanging: true, requestBody: jsonBody(null), description: 'Body: { user_id, currency? }. Opens an account without a plan and without an entry, in the household currency of that moment; an optional `currency` that is not the household currency is 400 with `reason: "currency_mismatch"`. Answers 201 with { user_id, balance_minor: 0, currency, minor_unit, plan: null }. The member then sees the account (balance zero) and can file requests. Only household members: 400 otherwise, 409 with `reason: "account_deactivated"` for a deactivated member, 404 for an unknown user, 409 with `reason: "money_account_exists"` if there is one already. A first plan (PUT /rewards/money/plans/{userId}) or a first credit (POST /rewards/money/entries) opens the account as well.' }),
    },
    '/api/v1/rewards/money/accounts/{userId}': {
      delete: op({ summary: 'Close an empty pocket money account', tag: 'Rewards', admin: true, params: [idParam('userId', 'User ID')], stateChanging: true, description: 'Only an EMPTY account can be closed: no plan, balance zero, no open money request (`closable: true` in GET /rewards/money says so). Otherwise 409 with `reason: "money_account_not_empty"`; 404 without an account. Entries and decided requests stay as history. An account opened again takes the household currency of that moment - closing and reopening is the only way an account changes its currency.' }),
    },
    '/api/v1/rewards/money/ledger': {
      get: op({ summary: 'Pocket money history (filter by user_id)', tag: 'Rewards', description: 'Money entries only, under the same visibility rule as GET /rewards/money, applied in the query: `user_id` is a filter, not a right, and asking for somebody else answers an empty list. Each entry carries `delta` (minor units, signed) with its own `currency` and `minor_unit`, `type`, `reason`, `allowance_date` (the due date a scheduled credit was booked for, otherwise null) and `request_kind` (`withdrawal` or `deposit` when the entry came from a request).' }),
    },
    '/api/v1/rewards/money/entries': {
      post: op({ summary: 'Book pocket money directly (credit or debit)', tag: 'Rewards', admin: true, stateChanging: true, requestBody: jsonBody(null), description: 'Body: { user_id, amount, direction: "credit" | "debit", reason? }. `amount` is a decimal string. A first CREDIT opens the account in the household currency of that moment if there is none yet (POST /rewards/money/accounts opens one without booking anything); only household members can have one. An optional `currency` must be the currency of the account, otherwise 400 with `reason: "currency_mismatch"`; `amount` is read in the decimals of the account currency. The answer names `currency` and `minor_unit`. For the account of a DEACTIVATED member only `debit` is allowed (pay out what is left, never below zero); a credit is 409 with `reason: "account_deactivated"`. A debit above the balance is 400 with `reason: "insufficient_funds"` - there is no overdraft. `amount` and `reason` must be strings. A single amount is limited to 10^12 minor units, whatever the currency. No budget entry is created.' }),
    },
    '/api/v1/rewards/money/plans/{userId}': {
      put: op({ summary: 'Create or change the scheduled credit of a member', tag: 'Rewards', admin: true, params: [idParam('userId', 'User ID')], stateChanging: true, requestBody: jsonBody(null), description: 'Body: { amount, frequency: "weekly" | "monthly", anchor_day, paused? }. `anchor_day` is the day of the month (1-31) for a monthly plan and the weekday (1 = Monday to 7 = Sunday) for a weekly one. A month without the anchor day takes its last day and the day comes back afterwards (31 -> 28/29 -> 31). Due dates missed while the server was off are booked afterwards, each exactly once; a paused plan books nothing and skips its missed dates when it is resumed. A plan whose member is no longer part of the household is paused instead of credited. Changing only the amount keeps the next date. Dates that are due when the plan is changed are booked first, with the plan as it was, in the same transaction as the change - a new amount or a new anchor day never reaches back. `paused` left out keeps the stored state: a paused plan stays paused. The plan keeps the currency of the account; an optional `currency` that differs is 400 with `reason: "currency_mismatch"`. The plan of a deactivated member stays paused: changing or resuming it is 409 with `reason: "account_deactivated"`. A single amount is limited to 10^12 minor units.' }),
      delete: op({ summary: 'End the scheduled credit of a member', tag: 'Rewards', admin: true, params: [idParam('userId', 'User ID')], stateChanging: true, description: 'Removes the plan. Balance and history stay.' }),
    },
  };
}
