#!/usr/bin/env node
/**
 * Oikos Web Installer — temporary setup server.
 * Zero npm dependencies. Node.js built-ins only.
 * Run: node tools/installer/install-server.js
 */

import http from 'node:http';
import { readFileSync, writeFileSync, existsSync, copyFileSync } from 'node:fs';
import { spawn } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ENV_SCHEMA } from './env-schema.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DEFAULT_ROOT = resolve(__dirname, '..', '..');
const PORT = 8090;
const IDLE_TIMEOUT_MS = 30 * 60 * 1000;

// Resolved lazily so tests can point the installer at a temp directory.
function projectRoot() {
  return process.env.OIKOS_INSTALLER_ROOT
    ? resolve(process.env.OIKOS_INSTALLER_ROOT)
    : DEFAULT_ROOT;
}

const WRITABLE_KEYS = new Set(ENV_SCHEMA.filter(e => e.writeToEnv).map(e => e.key));

let idleTimer = null;

function resetIdle(server) {
  clearTimeout(idleTimer);
  idleTimer = setTimeout(() => {
    console.log('\nIdle timeout — shutting down installer server.');
    server.close(() => process.exit(0));
  }, IDLE_TIMEOUT_MS);
  // Don't let the idle timer keep the process (or a test runner) alive.
  idleTimer.unref?.();
}

/**
 * Allowlist env keys against ENV_SCHEMA and reject values that would inject
 * extra lines into the .env file. Returns { ok, env } or { ok: false, error }.
 */
export function sanitizeEnv(env) {
  const clean = {};
  for (const [key, value] of Object.entries(env || {})) {
    if (!WRITABLE_KEYS.has(key)) continue;          // drop unknown keys
    if (value == null || value === '') continue;    // skip empties
    const str = String(value);
    if (/[\n\r]/.test(str)) {
      return { ok: false, error: `Invalid value for ${key}: line breaks are not allowed` };
    }
    clean[key] = str;
  }
  return { ok: true, env: clean };
}

export function renderEnvFile(env) {
  const lines = ['# Generated by Oikos Installer'];
  for (const [key, value] of Object.entries(env)) lines.push(`${key}=${value}`);
  return lines.join('\n') + '\n';
}

/**
 * Copy an existing .env to .env.bak-<ISO timestamp> before it is overwritten.
 * Returns the backup path, or null when there was nothing to back up.
 * Throws on copy failure so the caller can refuse to overwrite.
 */
export function backupEnvFile(envPath) {
  if (!existsSync(envPath)) return null;
  const stamp = new Date().toISOString().replace(/:/g, '-');
  const backupPath = `${envPath}.bak-${stamp}`;
  copyFileSync(envPath, backupPath);
  return backupPath;
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', chunk => { data += chunk; });
    req.on('end', () => {
      try { resolve(JSON.parse(data || '{}')); } catch { reject(new Error('Invalid JSON')); }
    });
    req.on('error', reject);
  });
}

function json(res, status, body) {
  const payload = JSON.stringify(body);
  res.writeHead(status, {
    'Content-Type': 'application/json',
    'Content-Length': Buffer.byteLength(payload),
    'Cache-Control': 'no-store',
  });
  res.end(payload);
}

/**
 * Serve a read-only file from the repo's public/ tree so the installer can
 * reuse the app's design tokens and fonts. Missing files yield a 404 instead
 * of throwing, keeping the route handler exception-free.
 */
function serveStatic(res, filePath, contentType) {
  try {
    const body = readFileSync(filePath);
    res.writeHead(200, {
      'Content-Type': contentType,
      'Content-Length': body.length,
      'Cache-Control': 'no-store',
    });
    res.end(body);
  } catch {
    json(res, 404, { error: 'Not found' });
  }
}


async function route(req, res, server) {
  resetIdle(server);
  const url = new URL(req.url, `http://localhost:${PORT}`);

  if (req.method === 'GET' && url.pathname === '/') {
    const html = readFileSync(resolve(__dirname, 'install.html'));
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': html.length, 'Cache-Control': 'no-store' });
    res.end(html);
    return;
  }

  // App-Designtokens, read-only aus dem Repo (Phase 3: Token-Angleich).
  if (req.method === 'GET' && url.pathname === '/tokens.css') {
    return serveStatic(res, resolve(projectRoot(), 'public', 'styles', 'tokens.css'), 'text/css; charset=utf-8');
  }

  // Selbstgehostete Variable Fonts. basename() neutralisiert Path-Traversal;
  // nur .woff2 aus public/fonts wird ausgeliefert.
  if (req.method === 'GET' && url.pathname.startsWith('/fonts/') && url.pathname.endsWith('.woff2')) {
    const name = basename(url.pathname);
    return serveStatic(res, resolve(projectRoot(), 'public', 'fonts', name), 'font/woff2');
  }

  if (req.method === 'GET' && url.pathname === '/api/defaults') {
    return json(res, 200, { catalog: ENV_SCHEMA });
  }

  if (req.method === 'POST' && url.pathname === '/api/generate-secret') {
    return json(res, 200, { secret: randomBytes(32).toString('hex') });
  }

  if (req.method === 'GET' && url.pathname === '/api/preflight') {
    try {
      const envExists = existsSync(resolve(projectRoot(), '.env'));
      return await new Promise(resolvePromise => {
        const inspect = spawn('docker', ['inspect', '--format', '{{.State.Status}}', 'oikos'], { stdio: 'pipe' });
        let out = '';
        let settled = false;
        const reply = containerRunning => {
          if (settled) return;          // error + close can both fire
          settled = true;
          resolvePromise(json(res, 200, { envExists, containerRunning }));
        };
        inspect.stdout.on('data', d => { out += d.toString().trim(); });
        inspect.on('error', () => reply(false));
        inspect.on('close', code => reply(code === 0 && out === 'running'));
      });
    } catch (err) {
      return json(res, 500, { error: err.message });
    }
  }

  if (req.method === 'POST' && url.pathname === '/api/save-env') {
    try {
      const body = await readBody(req);
      const result = sanitizeEnv(body.env);
      if (!result.ok) return json(res, 400, { error: result.error });

      const envPath = resolve(projectRoot(), '.env');
      let backup = null;
      try {
        backup = backupEnvFile(envPath);
      } catch (err) {
        // Refuse to overwrite if we cannot secure a backup first.
        return json(res, 500, { error: `Could not back up existing .env: ${err.message}` });
      }

      writeFileSync(envPath, renderEnvFile(result.env), 'utf8');
      return json(res, 200, { ok: true, backup });
    } catch (err) {
      return json(res, 500, { error: err.message });
    }
  }

  if (req.method === 'POST' && url.pathname === '/api/start') {
    const child = spawn('docker', ['compose', 'up', '-d'], { cwd: projectRoot(), stdio: 'pipe' });
    child.on('error', err => console.error('docker compose error:', err.message));
    return json(res, 200, { ok: true });
  }

  if (req.method === 'GET' && url.pathname === '/api/status') {
    return new Promise(resolvePromise => {
      const inspect = spawn('docker', ['inspect', '--format', '{{.State.Health.Status}}', 'oikos'], { stdio: 'pipe' });
      let out = '';
      inspect.stdout.on('data', d => { out += d.toString().trim(); });
      inspect.on('close', code => {
        if (code === 0 && out === 'healthy') return resolvePromise(json(res, 200, { status: 'running' }));
        if (code === 0 && (out === 'starting' || out === 'unhealthy')) return resolvePromise(json(res, 200, { status: 'starting' }));
        const state = spawn('docker', ['inspect', '--format', '{{.State.Status}}', 'oikos'], { stdio: 'pipe' });
        let stateOut = '';
        state.stdout.on('data', d => { stateOut += d.toString().trim(); });
        state.on('close', () => {
          if (stateOut === 'running') return resolvePromise(json(res, 200, { status: 'starting' }));
          const logs = spawn('docker', ['compose', 'logs', '--tail', '30'], { cwd: projectRoot(), stdio: 'pipe' });
          let logsOut = '';
          logs.stdout.on('data', d => { logsOut += d.toString(); });
          logs.stderr.on('data', d => { logsOut += d.toString(); });
          logs.on('close', () => resolvePromise(json(res, 200, { status: 'error', logs: logsOut })));
        });
      });
    });
  }

  if (req.method === 'POST' && url.pathname === '/api/create-admin') {
    try {
      const body = await readBody(req);
      const oikosPort = body.port || 3000;
      const payload = JSON.stringify({
        username: body.username,
        display_name: body.display_name,
        password: body.password,
      });

      const result = await new Promise((resolve, reject) => {
        const opts = {
          hostname: 'localhost', port: oikosPort,
          path: '/api/v1/auth/setup', method: 'POST',
          headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(payload) },
        };
        const proxyReq = http.request(opts, proxyRes => {
          let data = '';
          proxyRes.on('data', d => { data += d; });
          proxyRes.on('end', () => {
            try { resolve({ status: proxyRes.statusCode, body: JSON.parse(data) }); }
            catch { resolve({ status: proxyRes.statusCode, body: { error: 'Invalid response from Oikos' } }); }
          });
        });
        proxyReq.on('error', reject);
        proxyReq.write(payload);
        proxyReq.end();
      });

      json(res, result.status, result.body);

      if (result.status === 201 || result.status === 403) {
        setTimeout(() => {
          console.log('\nSetup complete — shutting down installer server.');
          server.close(() => process.exit(0));
        }, 2000);
      }
    } catch (err) {
      json(res, 500, { error: err.message });
    }
    return;
  }

  json(res, 404, { error: 'Not found' });
}

export function createInstallerServer() {
  const server = http.createServer((req, res) => {
    route(req, res, server).catch(err => json(res, 500, { error: err.message }));
  });
  return server;
}

// Only start listening when run directly (not when imported by tests).
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const server = createInstallerServer();
  server.listen(PORT, '127.0.0.1', () => {
    console.log(`\n  Oikos Web Installer`);
    console.log(`  Open: http://localhost:${PORT}\n`);
    resetIdle(server);
  });
}
